// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TQ.Data.FeeCalculator;

namespace TQ.Data.FeeCalculator.Migrations
{
    [DbContext(typeof(FeeCalculatorContext))]
    [Migration("20200504102324_SeedTypeData")]
    partial class SeedTypeData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TQ.Data.FeeCalculator.Schemas.Dbo.Answer", b =>
                {
                    b.Property<Guid>("AnswerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ParameterAnswer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParameterName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RowNo")
                        .HasColumnType("int");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SessionType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AnswerId");

                    b.ToTable("Answers","dbo");
                });

            modelBuilder.Entity("TQ.Data.FeeCalculator.Schemas.Dbo.Category", b =>
                {
                    b.Property<Guid>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories","dbo");

                    b.HasData(
                        new
                        {
                            CategoryId = new Guid("6abc716e-7481-4993-84de-da80a385d096"),
                            CategoryName = "FeeRules",
                            Sequence = 1
                        },
                        new
                        {
                            CategoryId = new Guid("98e61c33-50c3-4540-8be7-e5c28ea5a664"),
                            CategoryName = "ConcessionRules",
                            Sequence = 2
                        },
                        new
                        {
                            CategoryId = new Guid("a8d9d6a1-263d-4ccb-a328-2547846f3122"),
                            CategoryName = "ServiceChargeRules",
                            Sequence = 3
                        });
                });

            modelBuilder.Entity("TQ.Data.FeeCalculator.Schemas.Dbo.DefPackage", b =>
                {
                    b.Property<Guid>("DefPackageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DefPackageId");

                    b.ToTable("DefPackages","dbo");
                });

            modelBuilder.Entity("TQ.Data.FeeCalculator.Schemas.Dbo.OutputOperationType", b =>
                {
                    b.Property<Guid>("OutputOperationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OutputOperationId");

                    b.ToTable("OutputOperationTypes","dbo");

                    b.HasData(
                        new
                        {
                            OutputOperationId = new Guid("10380bc9-98dd-49c2-b9ca-b0d316f9707a"),
                            Name = "add"
                        },
                        new
                        {
                            OutputOperationId = new Guid("ccfcb7fc-4705-4cf6-904e-cd2bc382ab9e"),
                            Name = "overwrite"
                        });
                });

            modelBuilder.Entity("TQ.Data.FeeCalculator.Schemas.Dbo.ParamDataType", b =>
                {
                    b.Property<Guid>("ParamDataTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ParamDataTypeName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ParamDataTypeId");

                    b.ToTable("ParamDataTypes","dbo");

                    b.HasData(
                        new
                        {
                            ParamDataTypeId = new Guid("d97c5bd8-a109-49a8-ba5d-c9ee3ebdff44"),
                            ParamDataTypeName = "bool"
                        },
                        new
                        {
                            ParamDataTypeId = new Guid("835187eb-99cf-4077-94d7-369d0fd4ecd7"),
                            ParamDataTypeName = "number"
                        },
                        new
                        {
                            ParamDataTypeId = new Guid("c44ec053-0681-449b-9c1b-b5d86782f645"),
                            ParamDataTypeName = "int"
                        },
                        new
                        {
                            ParamDataTypeId = new Guid("2eba37d4-be44-4fc7-bb92-ed583d044917"),
                            ParamDataTypeName = "string"
                        });
                });

            modelBuilder.Entity("TQ.Data.FeeCalculator.Schemas.Dbo.Parameter", b =>
                {
                    b.Property<Guid>("ParameterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MasterValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ParamDataTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Product")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tenant")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ParameterId");

                    b.HasIndex("ParamDataTypeId");

                    b.ToTable("Parameters","dbo");
                });

            modelBuilder.Entity("TQ.Data.FeeCalculator.Schemas.Dbo.ParameterType", b =>
                {
                    b.Property<Guid>("ParameterTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ParameterTypeId");

                    b.ToTable("ParameterTypes","dbo");

                    b.HasData(
                        new
                        {
                            ParameterTypeId = new Guid("6c6b863f-728f-444c-802c-d1b66d92d7f3"),
                            Name = "in"
                        },
                        new
                        {
                            ParameterTypeId = new Guid("7e4f3023-43bb-41dc-9cf5-7f873a04c2fc"),
                            Name = "out"
                        });
                });

            modelBuilder.Entity("TQ.Data.FeeCalculator.Schemas.Dbo.QSCollectionTypeRuleMapping", b =>
                {
                    b.Property<Guid>("QSCollectionTypeRuleMappingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ApplicationTypeRefNo")
                        .HasColumnType("int");

                    b.Property<string>("QSCollectionVersion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RuleDefId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("QSCollectionTypeRuleMappingId");

                    b.HasIndex("RuleDefId");

                    b.ToTable("QSCollectionTypeRuleMappings","dbo");
                });

            modelBuilder.Entity("TQ.Data.FeeCalculator.Schemas.Dbo.QSRuleMapping", b =>
                {
                    b.Property<Guid>("QSRuleMappingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("QSNo")
                        .HasColumnType("int");

                    b.Property<string>("QSVersion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RuleDefId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("QSRuleMappingId");

                    b.HasIndex("RuleDefId");

                    b.ToTable("QsRuleMapping","dbo");
                });

            modelBuilder.Entity("TQ.Data.FeeCalculator.Schemas.Dbo.Qsr", b =>
                {
                    b.Property<Guid>("QsrId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("QSCollectionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("QsrId");

                    b.ToTable("Qsr","dbo");
                });

            modelBuilder.Entity("TQ.Data.FeeCalculator.Schemas.Dbo.RuleDef", b =>
                {
                    b.Property<Guid>("RuleDefId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DefPackageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Product")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReferenceId")
                        .HasColumnType("int");

                    b.Property<string>("RuleDefinition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RuleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Tenant")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RuleDefId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("DefPackageId");

                    b.ToTable("RuleDefs","dbo");
                });

            modelBuilder.Entity("TQ.Data.FeeCalculator.Schemas.Dbo.RuleDefParameterMapping", b =>
                {
                    b.Property<Guid>("RuleDefParameterMappingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("OutputOperation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ParameterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ParameterType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RuleDefId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.HasKey("RuleDefParameterMappingId");

                    b.HasIndex("ParameterId");

                    b.HasIndex("RuleDefId");

                    b.ToTable("RuleDefParameterMappings","dbo");
                });

            modelBuilder.Entity("TQ.Data.FeeCalculator.Schemas.Dbo.SessionType", b =>
                {
                    b.Property<Guid>("SessionTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SessionTypeId");

                    b.ToTable("SessionTypes","dbo");

                    b.HasData(
                        new
                        {
                            SessionTypeId = new Guid("1145d244-fea5-45b0-9927-9c21dcd34566"),
                            Name = "TestSet"
                        },
                        new
                        {
                            SessionTypeId = new Guid("024512ec-6b91-4165-bb6a-0cfe9dc0965c"),
                            Name = "QSR"
                        });
                });

            modelBuilder.Entity("TQ.Data.FeeCalculator.Schemas.Dbo.Step", b =>
                {
                    b.Property<Guid>("StepId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ApplicationTypeRefId")
                        .HasColumnType("int");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Inputs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsFinalOutput")
                        .HasColumnType("bit");

                    b.Property<string>("Output")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OutputDataType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OutputParamName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RuleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RuleNo")
                        .HasColumnType("int");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SessionType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StepId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("RuleId");

                    b.ToTable("Steps","dbo");
                });

            modelBuilder.Entity("TQ.Data.FeeCalculator.Schemas.Dbo.TestSetHeader", b =>
                {
                    b.Property<Guid>("TestSetHeaderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TestSetHeaderId");

                    b.ToTable("TestSetHeaders","dbo");
                });

            modelBuilder.Entity("TQ.Data.FeeCalculator.Schemas.Dbo.Parameter", b =>
                {
                    b.HasOne("TQ.Data.FeeCalculator.Schemas.Dbo.ParamDataType", "ParamDataType")
                        .WithMany()
                        .HasForeignKey("ParamDataTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TQ.Data.FeeCalculator.Schemas.Dbo.QSCollectionTypeRuleMapping", b =>
                {
                    b.HasOne("TQ.Data.FeeCalculator.Schemas.Dbo.RuleDef", "RuleDef")
                        .WithMany()
                        .HasForeignKey("RuleDefId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TQ.Data.FeeCalculator.Schemas.Dbo.QSRuleMapping", b =>
                {
                    b.HasOne("TQ.Data.FeeCalculator.Schemas.Dbo.RuleDef", "RuleDef")
                        .WithMany()
                        .HasForeignKey("RuleDefId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TQ.Data.FeeCalculator.Schemas.Dbo.RuleDef", b =>
                {
                    b.HasOne("TQ.Data.FeeCalculator.Schemas.Dbo.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TQ.Data.FeeCalculator.Schemas.Dbo.DefPackage", "DefPackage")
                        .WithMany()
                        .HasForeignKey("DefPackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TQ.Data.FeeCalculator.Schemas.Dbo.RuleDefParameterMapping", b =>
                {
                    b.HasOne("TQ.Data.FeeCalculator.Schemas.Dbo.Parameter", "Parameter")
                        .WithMany("RuleDefParameterMappings")
                        .HasForeignKey("ParameterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TQ.Data.FeeCalculator.Schemas.Dbo.RuleDef", "RuleDef")
                        .WithMany("RuleDefParameterMappings")
                        .HasForeignKey("RuleDefId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TQ.Data.FeeCalculator.Schemas.Dbo.Step", b =>
                {
                    b.HasOne("TQ.Data.FeeCalculator.Schemas.Dbo.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TQ.Data.FeeCalculator.Schemas.Dbo.RuleDef", "RuleDef")
                        .WithMany()
                        .HasForeignKey("RuleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
