// <auto-generated />
using System;
using System.Diagnostics.CodeAnalysis;
using Microsoft.EntityFrameworkCore.Migrations;

namespace TQ.Data.Session.Migrations
{
    [ExcludeFromCodeCoverage]
    public partial class _909InitialSetup : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "UserApplications",
                columns: table => new
                {
                    UserApplicationId = table.Column<Guid>(nullable: false),
                    UserId = table.Column<Guid>(nullable: false),
                    ApplicationName = table.Column<string>(nullable: true),
                    PlanningFormId = table.Column<Guid>(nullable: false),
                    Started = table.Column<bool>(nullable: false),
                    LastSaved = table.Column<DateTime>(nullable: false),
                    Status = table.Column<string>(nullable: true),
                    Country = table.Column<string>(nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_UserApplications", x => x.UserApplicationId);
                });

            migrationBuilder.CreateTable(
                name: "QuestionSetResponses",
                columns: table => new
                {
                    QuestionSetResponseId = table.Column<Guid>(nullable: false),
                    UserApplicationId = table.Column<Guid>(nullable: false),
                    Response = table.Column<string>(nullable: true),
                    QuestionSetId = table.Column<Guid>(nullable: false),
                    LastSaved = table.Column<DateTime>(nullable: false),
                    ModifiedBy = table.Column<Guid>(nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_QuestionSetResponses", x => x.QuestionSetResponseId);
                    table.ForeignKey(
                        name: "FK_QuestionSetResponses_UserApplications_UserApplicationId",
                        column: x => x.UserApplicationId,
                        principalTable: "UserApplications",
                        principalColumn: "UserApplicationId",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "IX_QuestionSetResponses_UserApplicationId",
                table: "QuestionSetResponses",
                column: "UserApplicationId");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "QuestionSetResponses");

            migrationBuilder.DropTable(
                name: "UserApplications");
        }
    }
}
