// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;
using System;
using System.Diagnostics.CodeAnalysis;

namespace TQ.Data.FormEngine.Migrations
{
    [ExcludeFromCodeCoverage]
    public partial class _1221_Modified_FieldID_SectionId_Nullable : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_FieldConstraints_Fields_FieldId",
                schema: "forms",
                table: "FieldConstraints");

            migrationBuilder.AlterColumn<Guid>(
                name: "SectionId",
                schema: "forms",
                table: "FieldConstraints",
                nullable: true,
                oldClrType: typeof(Guid),
                oldType: "uniqueidentifier");

            migrationBuilder.AlterColumn<Guid>(
                name: "FieldId",
                schema: "forms",
                table: "FieldConstraints",
                nullable: true,
                oldClrType: typeof(Guid),
                oldType: "uniqueidentifier");

            migrationBuilder.AddForeignKey(
                name: "FK_FieldConstraints_Fields_FieldId",
                schema: "forms",
                table: "FieldConstraints",
                column: "FieldId",
                principalSchema: "forms",
                principalTable: "Fields",
                principalColumn: "FieldId",
                onDelete: ReferentialAction.Restrict);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_FieldConstraints_Fields_FieldId",
                schema: "forms",
                table: "FieldConstraints");

            migrationBuilder.AlterColumn<Guid>(
                name: "SectionId",
                schema: "forms",
                table: "FieldConstraints",
                type: "uniqueidentifier",
                nullable: false,
                oldClrType: typeof(Guid),
                oldNullable: true);

            migrationBuilder.AlterColumn<Guid>(
                name: "FieldId",
                schema: "forms",
                table: "FieldConstraints",
                type: "uniqueidentifier",
                nullable: false,
                oldClrType: typeof(Guid),
                oldNullable: true);

            migrationBuilder.AddForeignKey(
                name: "FK_FieldConstraints_Fields_FieldId",
                schema: "forms",
                table: "FieldConstraints",
                column: "FieldId",
                principalSchema: "forms",
                principalTable: "Fields",
                principalColumn: "FieldId",
                onDelete: ReferentialAction.Cascade);
        }
    }
}
