// <auto-generated />
using System;
using System.Diagnostics.CodeAnalysis;
using Microsoft.EntityFrameworkCore.Migrations;

namespace TQ.Data.FormEngine.Migrations
{
    [ExcludeFromCodeCoverage]
    public partial class _1140_Add_CreatedBy : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<Guid>(
                name: "CreatedBy",
                schema: "sessions",
                table: "QSRAnswers",
                nullable: false,
                defaultValue: new Guid("00000000-0000-0000-0000-000000000000"));

            migrationBuilder.AddColumn<Guid>(
                name: "CreatedBy",
                schema: "sessions",
                table: "QSR",
                nullable: false,
                defaultValue: new Guid("00000000-0000-0000-0000-000000000000"));

            migrationBuilder.AddColumn<DateTime>(
                name: "CreatedDate",
                schema: "sessions",
                table: "QSR",
                nullable: false,
                defaultValue: new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));

            migrationBuilder.AddColumn<Guid>(
                name: "CreatedBy",
                schema: "sessions",
                table: "QSCollections",
                nullable: false,
                defaultValue: new Guid("00000000-0000-0000-0000-000000000000"));

            migrationBuilder.AddColumn<Guid>(
                name: "CreatedBy",
                schema: "forms",
                table: "Sections",
                nullable: false,
                defaultValue: new Guid("00000000-0000-0000-0000-000000000000"));

            migrationBuilder.AddColumn<Guid>(
                name: "CreatedBy",
                schema: "forms",
                table: "QSCollectionTypes",
                nullable: false,
                defaultValue: new Guid("00000000-0000-0000-0000-000000000000"));

            migrationBuilder.AddColumn<Guid>(
                name: "CreatedBy",
                schema: "forms",
                table: "QS",
                nullable: false,
                defaultValue: new Guid("00000000-0000-0000-0000-000000000000"));

            migrationBuilder.AddColumn<Guid>(
                name: "CreatedBy",
                schema: "forms",
                table: "Fields",
                nullable: false,
                defaultValue: new Guid("00000000-0000-0000-0000-000000000000"));
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "CreatedBy",
                schema: "sessions",
                table: "QSRAnswers");

            migrationBuilder.DropColumn(
                name: "CreatedBy",
                schema: "sessions",
                table: "QSR");

            migrationBuilder.DropColumn(
                name: "CreatedDate",
                schema: "sessions",
                table: "QSR");

            migrationBuilder.DropColumn(
                name: "CreatedBy",
                schema: "sessions",
                table: "QSCollections");

            migrationBuilder.DropColumn(
                name: "CreatedBy",
                schema: "forms",
                table: "Sections");

            migrationBuilder.DropColumn(
                name: "CreatedBy",
                schema: "forms",
                table: "QSCollectionTypes");

            migrationBuilder.DropColumn(
                name: "CreatedBy",
                schema: "forms",
                table: "QS");

            migrationBuilder.DropColumn(
                name: "CreatedBy",
                schema: "forms",
                table: "Fields");
        }
    }
}
