// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;
using System.Diagnostics.CodeAnalysis;

namespace TQ.Data.FormEngine.Migrations
{
    [ExcludeFromCodeCoverage]
    public partial class _897_GetQsrFieldsforLatestVersion : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            var strGetQuestionSetbyIdProc = @"CREATE PROCEDURE [dbo].[GetQsrFieldsforLatestVersion] @QSRID UNIQUEIDENTIFIER 
             AS 
               BEGIN 
                   SELECT SFM.fieldid, 
                          QSRA.answer, 
                          SFM.fieldno 
                   FROM   [Forms].qs 
                          INNER JOIN [Sessions].qsr 
                                  ON qsr.qsno = qs.qsno 
                          INNER JOIN (SELECT Max(qs.qsversion) AS LatestVersion 
                                      FROM   [Forms].qs 
                                             INNER JOIN [Sessions].qsr 
                                                     ON qsr.qsno = qs.qsno 
                                      WHERE  qsr.qsrid = @QSRID 
                                             AND qs.statusid = 2) AS QSLatestVer 
                                  ON qs.qsversion = QSLatestVer.latestversion 
                          INNER JOIN [Forms].qssectionmappings QSM 
                                  ON QSM.qsid = qs.qsid 
                          INNER JOIN [Forms].sectionfieldmappings SFM 
                                  ON SFM.sectionid = QSM.sectionid 
                          INNER JOIN [Sessions].qsranswers QSRA 
                                  ON ( QSRA.qsrid = qsr.qsrid 
                                       AND QSRA.fieldno = SFM.fieldno ) 
                   WHERE  qsr.qsrid = @QSRID; 
               END";
            strGetQuestionSetbyIdProc = strGetQuestionSetbyIdProc.Replace("'", "''");
            migrationBuilder.Sql($"EXEC ('{strGetQuestionSetbyIdProc}')");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            var strGetQuestionSetbyIdProc = "DROP PROCEDURE [dbo].[GetQsrFieldsforLatestVersion];";
            strGetQuestionSetbyIdProc = strGetQuestionSetbyIdProc.Replace("'", "''");
            migrationBuilder.Sql($"EXEC ('{strGetQuestionSetbyIdProc}')");
        }
    }
}
