// <auto-generated />
using System;
using System.Diagnostics.CodeAnalysis;
using Microsoft.EntityFrameworkCore.Migrations;

namespace TQ.Data.FormEngine.Migrations
{
    [ExcludeFromCodeCoverage]
    public partial class _1692_CreateTaxonomyTable : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "Taxonomy",
                schema: "forms",
                columns: table => new
                {
                    TaxonomyID = table.Column<Guid>(nullable: false),
                    Product = table.Column<string>(nullable: true),
                    Tenant = table.Column<string>(nullable: true),
                    LanguageCode = table.Column<string>(nullable: true),
                    QsNo = table.Column<int>(nullable: false),
                    QsVersion = table.Column<string>(nullable: true),
                    TaxonomyDictionary = table.Column<string>(nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Taxonomy", x => x.TaxonomyID);
                });
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "Taxonomy",
                schema: "forms");
        }
    }
}
