// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;
using System;
using System.Diagnostics.CodeAnalysis;

namespace TQ.Data.FormEngine.Migrations
{
    [ExcludeFromCodeCoverage]
    public partial class _894_addedNewColumnForDepends : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "SubSectionId",
                schema: "forms",
                table: "FieldConstraints");

            migrationBuilder.AddColumn<int>(
                name: "SectionNo",
                schema: "forms",
                table: "Sections",
                nullable: false,
                defaultValue: 0);

            migrationBuilder.AddColumn<string>(
                name: "Product",
                schema: "forms",
                table: "QSCollectionTypes",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "Tenant",
                schema: "forms",
                table: "QSCollectionTypes",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "Product",
                schema: "forms",
                table: "QS",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "Tenant",
                schema: "forms",
                table: "QS",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "ToBeRedacted",
                schema: "forms",
                table: "Fields",
                nullable: true);

            migrationBuilder.AlterColumn<Guid>(
                name: "DependantAnswerGuideId",
                schema: "forms",
                table: "FieldConstraints",
                nullable: false,
                oldClrType: typeof(string),
                oldType: "nvarchar(max)",
                oldNullable: true);

            migrationBuilder.AddColumn<int>(
                name: "DependantAnswerGuideNo",
                schema: "forms",
                table: "FieldConstraints",
                nullable: true);

            migrationBuilder.AddColumn<int>(
                name: "DependantAnswerQSNo",
                schema: "forms",
                table: "FieldConstraints",
                nullable: true);

            migrationBuilder.AddColumn<Guid>(
                name: "SectionId",
                schema: "forms",
                table: "FieldConstraints",
                nullable: false,
                defaultValue: new Guid("00000000-0000-0000-0000-000000000000"));

            migrationBuilder.AddColumn<int>(
                name: "SectionNo",
                schema: "forms",
                table: "FieldConstraints",
                nullable: true);

            migrationBuilder.AddColumn<int>(
                name: "AnswerGuideNo",
                schema: "forms",
                table: "AnswerGuides",
                nullable: false,
                defaultValue: 0);

            migrationBuilder.AddColumn<int>(
                name: "CopyFromFieldNo",
                schema: "forms",
                table: "AnswerGuides",
                nullable: true);

            migrationBuilder.AddColumn<int>(
                name: "CopyFromQSNo",
                schema: "forms",
                table: "AnswerGuides",
                nullable: true);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "SectionNo",
                schema: "forms",
                table: "Sections");

            migrationBuilder.DropColumn(
                name: "Product",
                schema: "forms",
                table: "QSCollectionTypes");

            migrationBuilder.DropColumn(
                name: "Tenant",
                schema: "forms",
                table: "QSCollectionTypes");

            migrationBuilder.DropColumn(
                name: "Product",
                schema: "forms",
                table: "QS");

            migrationBuilder.DropColumn(
                name: "Tenant",
                schema: "forms",
                table: "QS");

            migrationBuilder.DropColumn(
                name: "ToBeRedacted",
                schema: "forms",
                table: "Fields");

            migrationBuilder.DropColumn(
                name: "DependantAnswerGuideNo",
                schema: "forms",
                table: "FieldConstraints");

            migrationBuilder.DropColumn(
                name: "DependantAnswerQSNo",
                schema: "forms",
                table: "FieldConstraints");

            migrationBuilder.DropColumn(
                name: "SectionId",
                schema: "forms",
                table: "FieldConstraints");

            migrationBuilder.DropColumn(
                name: "SectionNo",
                schema: "forms",
                table: "FieldConstraints");

            migrationBuilder.DropColumn(
                name: "AnswerGuideNo",
                schema: "forms",
                table: "AnswerGuides");

            migrationBuilder.DropColumn(
                name: "CopyFromFieldNo",
                schema: "forms",
                table: "AnswerGuides");

            migrationBuilder.DropColumn(
                name: "CopyFromQSNo",
                schema: "forms",
                table: "AnswerGuides");

            migrationBuilder.AlterColumn<string>(
                name: "DependantAnswerGuideId",
                schema: "forms",
                table: "FieldConstraints",
                type: "nvarchar(max)",
                nullable: true,
                oldClrType: typeof(Guid));

            migrationBuilder.AddColumn<string>(
                name: "SubSectionId",
                schema: "forms",
                table: "FieldConstraints",
                type: "nvarchar(max)",
                nullable: true);
        }
    }
}
