// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TQ.Data.FormEngine;

namespace TQ.Data.FormEngine.Migrations
{
    [DbContext(typeof(FormsEngineContext))]
    [Migration("20200219065451_894_CreateFormEngineSchemaTables")]
    partial class _894_CreateFormEngineSchemaTables
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TQ.Data.FormEngine.Schemas.Dbo.ApplicationQuestionSetMapping", b =>
                {
                    b.Property<Guid>("MappingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApplicationTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<Guid>("QuestionSetId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("MappingId");

                    b.HasIndex("ApplicationTypeId");

                    b.HasIndex("QuestionSetId");

                    b.ToTable("ApplicationQuestionSetMappings","dbo");
                });

            modelBuilder.Entity("TQ.Data.FormEngine.Schemas.Dbo.ApplicationType", b =>
                {
                    b.Property<Guid>("ApplicationTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ApplicationTypeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ApplicationTypeId");

                    b.ToTable("ApplicationTypes","dbo");
                });

            modelBuilder.Entity("TQ.Data.FormEngine.Schemas.Dbo.QuestionSet", b =>
                {
                    b.Property<Guid>("QuestionSetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Definition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("LanguageId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("QuestionSetId");

                    b.ToTable("QuestionSets","dbo");
                });

            modelBuilder.Entity("TQ.Data.FormEngine.Schemas.Forms.AnswerGuide", b =>
                {
                    b.Property<Guid>("AnswerGuideId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AnswerTypeId")
                        .HasColumnType("int");

                    b.Property<string>("ErrLabel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("FieldId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("IsDefault")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Label")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Max")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Min")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AnswerGuideId");

                    b.HasIndex("AnswerTypeId");

                    b.HasIndex("FieldId");

                    b.ToTable("AnswerGuides","forms");
                });

            modelBuilder.Entity("TQ.Data.FormEngine.Schemas.Forms.AnswerType", b =>
                {
                    b.Property<int>("AnswerTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AnswerTypes")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AnswerTypeId");

                    b.ToTable("AnswerTypes","forms");
                });

            modelBuilder.Entity("TQ.Data.FormEngine.Schemas.Forms.Constraint", b =>
                {
                    b.Property<int>("ConstraintId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Constraints")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ConstraintId");

                    b.ToTable("Constraints","forms");
                });

            modelBuilder.Entity("TQ.Data.FormEngine.Schemas.Forms.Display", b =>
                {
                    b.Property<int>("DisplayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Displays")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DisplayId");

                    b.ToTable("Displays","forms");
                });

            modelBuilder.Entity("TQ.Data.FormEngine.Schemas.Forms.Field", b =>
                {
                    b.Property<Guid>("FieldId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("AnswerRuleCount")
                        .HasColumnType("int");

                    b.Property<int?>("AnswerRuleId")
                        .HasColumnType("int");

                    b.Property<int?>("ConstraintRuleCount")
                        .HasColumnType("int");

                    b.Property<int?>("ConstraintRuleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DisplayConstraintId")
                        .HasColumnType("int");

                    b.Property<int?>("DisplayId")
                        .HasColumnType("int");

                    b.Property<int>("FieldNo")
                        .HasColumnType("int");

                    b.Property<int?>("FieldTypeId")
                        .HasColumnType("int");

                    b.Property<string>("FieldVersion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Helptext")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Label")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Parameter")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FieldId");

                    b.HasIndex("AnswerRuleId");

                    b.HasIndex("ConstraintRuleId");

                    b.HasIndex("DisplayConstraintId");

                    b.HasIndex("DisplayId");

                    b.HasIndex("FieldTypeId");

                    b.ToTable("Fields","forms");
                });

            modelBuilder.Entity("TQ.Data.FormEngine.Schemas.Forms.FieldAggregation", b =>
                {
                    b.Property<Guid>("FieldAggregationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AggregatedFieldId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FieldId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("FunctionId")
                        .HasColumnType("int");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.HasKey("FieldAggregationId");

                    b.HasIndex("FieldId");

                    b.HasIndex("FunctionId");

                    b.ToTable("FieldAggregations","forms");
                });

            modelBuilder.Entity("TQ.Data.FormEngine.Schemas.Forms.FieldConstraint", b =>
                {
                    b.Property<Guid>("FieldConstraintId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DependantAnswerGuideId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("FieldId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SubSectionId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FieldConstraintId");

                    b.HasIndex("FieldId");

                    b.ToTable("FieldConstraints","forms");
                });

            modelBuilder.Entity("TQ.Data.FormEngine.Schemas.Forms.FieldType", b =>
                {
                    b.Property<int>("FieldTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FieldTypes")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FieldTypeId");

                    b.ToTable("FieldTypes","forms");
                });

            modelBuilder.Entity("TQ.Data.FormEngine.Schemas.Forms.Function", b =>
                {
                    b.Property<int>("FunctionsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Functions")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FunctionsId");

                    b.ToTable("Functions","forms");
                });

            modelBuilder.Entity("TQ.Data.FormEngine.Schemas.Forms.QS", b =>
                {
                    b.Property<Guid>("QSId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Helptext")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Label")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("QSName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QSNo")
                        .HasColumnType("int");

                    b.Property<int?>("QSTypeId")
                        .HasColumnType("int");

                    b.Property<string>("QSVersion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<string>("TaxonomyLocation")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("QSId");

                    b.HasIndex("QSTypeId");

                    b.HasIndex("StatusId");

                    b.ToTable("QS","forms");
                });

            modelBuilder.Entity("TQ.Data.FormEngine.Schemas.Forms.QSCollectionMapping", b =>
                {
                    b.Property<Guid>("QSCollectionMappingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("QSCollectionTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("QSId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("QSNo")
                        .HasColumnType("int");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.HasKey("QSCollectionMappingId");

                    b.HasIndex("QSCollectionTypeId");

                    b.HasIndex("QSId");

                    b.ToTable("QSCollectionMappings","forms");
                });

            modelBuilder.Entity("TQ.Data.FormEngine.Schemas.Forms.QSCollectionType", b =>
                {
                    b.Property<Guid>("QSCollectionTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CountryCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Helptext")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Label")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("QSCollectionTypeId");

                    b.ToTable("QSCollectionTypes","forms");
                });

            modelBuilder.Entity("TQ.Data.FormEngine.Schemas.Forms.QSSectionMapping", b =>
                {
                    b.Property<Guid>("QSSectionMappingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("QSId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SectionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.HasKey("QSSectionMappingId");

                    b.HasIndex("QSId");

                    b.HasIndex("SectionId");

                    b.ToTable("QSSectionMappings","forms");
                });

            modelBuilder.Entity("TQ.Data.FormEngine.Schemas.Forms.QSType", b =>
                {
                    b.Property<int>("QSTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("QSTypes")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("QSTypeId");

                    b.ToTable("QSTypes","forms");
                });

            modelBuilder.Entity("TQ.Data.FormEngine.Schemas.Forms.Rule", b =>
                {
                    b.Property<int>("RuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Rules")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RuleId");

                    b.ToTable("Rules","forms");
                });

            modelBuilder.Entity("TQ.Data.FormEngine.Schemas.Forms.Section", b =>
                {
                    b.Property<Guid>("SectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Helptext")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Label")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("RuleCount")
                        .HasColumnType("int");

                    b.Property<int?>("RuleId")
                        .HasColumnType("int");

                    b.Property<int>("SectionTypeId")
                        .HasColumnType("int");

                    b.HasKey("SectionId");

                    b.HasIndex("RuleId");

                    b.HasIndex("SectionTypeId");

                    b.ToTable("Sections","forms");
                });

            modelBuilder.Entity("TQ.Data.FormEngine.Schemas.Forms.SectionFieldMapping", b =>
                {
                    b.Property<Guid>("SectionFieldMappingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FieldId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FieldNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SectionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.HasKey("SectionFieldMappingId");

                    b.HasIndex("FieldId");

                    b.HasIndex("SectionId");

                    b.ToTable("SectionFieldMappings","forms");
                });

            modelBuilder.Entity("TQ.Data.FormEngine.Schemas.Forms.SectionType", b =>
                {
                    b.Property<int>("SectionTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("SectionTypes")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SectionTypeId");

                    b.ToTable("SectionTypes","forms");
                });

            modelBuilder.Entity("TQ.Data.FormEngine.Schemas.Forms.Statuses", b =>
                {
                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StatusId");

                    b.ToTable("Status","forms");
                });

            modelBuilder.Entity("TQ.Data.FormEngine.Schemas.Sessions.QSCollection", b =>
                {
                    b.Property<Guid>("QSCollectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ApplicationName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CountryCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("QSCollectionTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RefNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("QSCollectionId");

                    b.HasIndex("QSCollectionTypeId");

                    b.ToTable("QSCollections","sessions");
                });

            modelBuilder.Entity("TQ.Data.FormEngine.Schemas.Sessions.Qsr", b =>
                {
                    b.Property<Guid>("QsrId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("QSCollectionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("QSId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("QSNo")
                        .HasColumnType("int");

                    b.Property<string>("QSVersion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("QsrId");

                    b.HasIndex("QSCollectionId");

                    b.HasIndex("QSId");

                    b.ToTable("QSR","sessions");
                });

            modelBuilder.Entity("TQ.Data.FormEngine.Schemas.Sessions.QsrAnswer", b =>
                {
                    b.Property<Guid>("QsrAnswerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Answer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("FieldId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("FieldNo")
                        .HasColumnType("int");

                    b.Property<Guid>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("QsrId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("QsrAnswerId");

                    b.HasIndex("FieldId");

                    b.HasIndex("QsrId");

                    b.ToTable("QSRAnswers","sessions");
                });

            modelBuilder.Entity("TQ.Data.FormEngine.Schemas.Dbo.ApplicationQuestionSetMapping", b =>
                {
                    b.HasOne("TQ.Data.FormEngine.Schemas.Dbo.ApplicationType", "ApplicationType")
                        .WithMany()
                        .HasForeignKey("ApplicationTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TQ.Data.FormEngine.Schemas.Dbo.QuestionSet", "QuestionSet")
                        .WithMany()
                        .HasForeignKey("QuestionSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TQ.Data.FormEngine.Schemas.Forms.AnswerGuide", b =>
                {
                    b.HasOne("TQ.Data.FormEngine.Schemas.Forms.AnswerType", "AnswerTypes")
                        .WithMany()
                        .HasForeignKey("AnswerTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TQ.Data.FormEngine.Schemas.Forms.Field", "Field")
                        .WithMany()
                        .HasForeignKey("FieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TQ.Data.FormEngine.Schemas.Forms.Field", b =>
                {
                    b.HasOne("TQ.Data.FormEngine.Schemas.Forms.Rule", "Rule")
                        .WithMany()
                        .HasForeignKey("AnswerRuleId");

                    b.HasOne("TQ.Data.FormEngine.Schemas.Forms.Rule", "Rules")
                        .WithMany()
                        .HasForeignKey("ConstraintRuleId");

                    b.HasOne("TQ.Data.FormEngine.Schemas.Forms.Constraint", "Constraint")
                        .WithMany()
                        .HasForeignKey("DisplayConstraintId");

                    b.HasOne("TQ.Data.FormEngine.Schemas.Forms.Display", "Display")
                        .WithMany()
                        .HasForeignKey("DisplayId");

                    b.HasOne("TQ.Data.FormEngine.Schemas.Forms.FieldType", "FieldType")
                        .WithMany()
                        .HasForeignKey("FieldTypeId");
                });

            modelBuilder.Entity("TQ.Data.FormEngine.Schemas.Forms.FieldAggregation", b =>
                {
                    b.HasOne("TQ.Data.FormEngine.Schemas.Forms.Field", "Field")
                        .WithMany()
                        .HasForeignKey("FieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TQ.Data.FormEngine.Schemas.Forms.Function", "Function")
                        .WithMany()
                        .HasForeignKey("FunctionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TQ.Data.FormEngine.Schemas.Forms.FieldConstraint", b =>
                {
                    b.HasOne("TQ.Data.FormEngine.Schemas.Forms.Field", "Field")
                        .WithMany()
                        .HasForeignKey("FieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TQ.Data.FormEngine.Schemas.Forms.QS", b =>
                {
                    b.HasOne("TQ.Data.FormEngine.Schemas.Forms.QSType", "QSType")
                        .WithMany()
                        .HasForeignKey("QSTypeId");

                    b.HasOne("TQ.Data.FormEngine.Schemas.Forms.Statuses", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TQ.Data.FormEngine.Schemas.Forms.QSCollectionMapping", b =>
                {
                    b.HasOne("TQ.Data.FormEngine.Schemas.Forms.QSCollectionType", "QSCollectionType")
                        .WithMany()
                        .HasForeignKey("QSCollectionTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TQ.Data.FormEngine.Schemas.Forms.QS", "QuestionSet")
                        .WithMany()
                        .HasForeignKey("QSId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TQ.Data.FormEngine.Schemas.Forms.QSSectionMapping", b =>
                {
                    b.HasOne("TQ.Data.FormEngine.Schemas.Forms.QS", "QuestionSet")
                        .WithMany()
                        .HasForeignKey("QSId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TQ.Data.FormEngine.Schemas.Forms.Section", "Section")
                        .WithMany()
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TQ.Data.FormEngine.Schemas.Forms.Section", b =>
                {
                    b.HasOne("TQ.Data.FormEngine.Schemas.Forms.Rule", "Rules")
                        .WithMany()
                        .HasForeignKey("RuleId");

                    b.HasOne("TQ.Data.FormEngine.Schemas.Forms.SectionType", "SectionType")
                        .WithMany()
                        .HasForeignKey("SectionTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TQ.Data.FormEngine.Schemas.Forms.SectionFieldMapping", b =>
                {
                    b.HasOne("TQ.Data.FormEngine.Schemas.Forms.Field", "Field")
                        .WithMany()
                        .HasForeignKey("FieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TQ.Data.FormEngine.Schemas.Forms.Section", "Section")
                        .WithMany()
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TQ.Data.FormEngine.Schemas.Sessions.QSCollection", b =>
                {
                    b.HasOne("TQ.Data.FormEngine.Schemas.Forms.QSCollectionType", "QSCollectionType")
                        .WithMany()
                        .HasForeignKey("QSCollectionTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TQ.Data.FormEngine.Schemas.Sessions.Qsr", b =>
                {
                    b.HasOne("TQ.Data.FormEngine.Schemas.Sessions.QSCollection", "QSCollection")
                        .WithMany()
                        .HasForeignKey("QSCollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TQ.Data.FormEngine.Schemas.Forms.QS", "QuestionSet")
                        .WithMany()
                        .HasForeignKey("QSId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TQ.Data.FormEngine.Schemas.Sessions.QsrAnswer", b =>
                {
                    b.HasOne("TQ.Data.FormEngine.Schemas.Forms.Field", "Field")
                        .WithMany()
                        .HasForeignKey("FieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TQ.Data.FormEngine.Schemas.Sessions.Qsr", "Qsr")
                        .WithMany()
                        .HasForeignKey("QsrId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
