// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;
using System.Diagnostics.CodeAnalysis;

namespace TQ.Data.FormEngine.Migrations
{
    [ExcludeFromCodeCoverage]
    public partial class _896_GetLatestVerQSbyQSCollectionTypeIdAlter : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            var strGetQuestionSetbyIdProc = @"ALTER PROCEDURE [dbo].[GetLatestVerQSbyQSCollectionTypeId]
                @QSCollectionTypeId uniqueidentifier
                
                AS
                
                BEGIN 
                    SELECT QSCM.QSId, 
                           QS.QSName, 
                           QSCM.QSNo, 
                           [sequence], 
                           QSVersion 
                    FROM   [Forms].QSCollectionMappings QSCM 
                           INNER JOIN [Forms].QS 
                                   ON QSCM.QSId = QS.QSId 
                           INNER JOIN (SELECT Max(QS.QSVersion) AS LatestVersion , QS.QSNo as VerQSno
                                       FROM   [Forms].QS
                                              INNER JOIN [Forms].QSCollectionMappings qsc 
                                                      ON qsc.qsno = QS.qsno 
                                       WHERE  qsc.QSCollectionTypeId = @QSCollectionTypeId 
                                              AND QS.statusid = 2
											   GROUP BY QS.QSNo
											  ) AS QSLatestVer 
                                   ON QS.qsversion = QSLatestVer.latestversion 
								   AND QS.qsno= QSLatestVer.VerQSno
                    WHERE  QSCM.qscollectiontypeid = @QSCollectionTypeId 
                			AND QS.StatusId=2
                    ORDER  BY [sequence] 
                END";
            strGetQuestionSetbyIdProc = strGetQuestionSetbyIdProc.Replace("'", "''");
            migrationBuilder.Sql($"EXEC ('{strGetQuestionSetbyIdProc}')");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            var strGetQuestionSetbyIdProc = @"ALTER PROCEDURE [dbo].[GetLatestVerQSbyQSCollectionTypeId]
            @QSCollectionTypeId uniqueidentifier
            
            AS
            
            BEGIN 
                SELECT QSCM.QSId, 
                       QS.QSName, 
                       QSCM.QSNo, 
                       [sequence], 
                       QSVersion 
                FROM   [Forms].QSCollectionMappings QSCM 
                       INNER JOIN [Forms].QS 
                               ON QSCM.QSId = QS.QSId 
                       INNER JOIN (SELECT Max(QS.QSVersion) AS LatestVersion 
                                   FROM   [Forms].QS
                                          INNER JOIN [Forms].QSCollectionMappings qsc 
                                                  ON qsc.qsno = QS.qsno 
                                   WHERE  qsc.QSCollectionTypeId = @QSCollectionTypeId 
                                          AND QS.statusid = 2) AS QSLatestVer 
                               ON QS.qsversion = QSLatestVer.latestversion 
                WHERE  QSCM.qscollectiontypeid = @QSCollectionTypeId 
            			AND QS.StatusId=2
                ORDER  BY [sequence] 
            END";
            strGetQuestionSetbyIdProc = strGetQuestionSetbyIdProc.Replace("'", "''");
            migrationBuilder.Sql($"EXEC ('{strGetQuestionSetbyIdProc}')");
        }
    }
}
